enum TinkoffInvestmentError {
  unknown(-1, 'UNKNOWN', 'Unknown error', 'Неизвестная ошибка'),
  e12001(12001, 'UNIMPLEMENTED', 'Method is unimplemented', 'Метод не реализован.'),
  e12002(12002, 'UNAVAILABLE', 'Deprecated method is unavailable', 'Метод устарел и недоступен.'),
  e30001(30001, 'INVALID_ARGUMENT', 'Missing parameter: from',
      'Входной параметр from является обязательным. Укажите корректный параметр from.'),
  e30002(30002, 'INVALID_ARGUMENT', 'The required period should not exceed 7 days',
      'Запрошенный период не может превышать 7 дней. Укажите корректный период.'),
  e30003(30003, 'INVALID_ARGUMENT', 'from can\'t be less than the current date',
      'Входной параметр from не может быть меньше текущей даты. Укажите корректный параметр from.'),
  e30004(30004, 'INVALID_ARGUMENT', 'Missing parameter: to',
      'Входной параметр to является обязательным. Укажите корректный параметр to.'),
  e30005(30005, 'INVALID_ARGUMENT', 'id_type is invalid', 'Входной параметр id_type имеет некорректное значение.'),
  e30006(30006, 'INVALID_ARGUMENT', 'Missing parameter: id_type',
      'Входной параметр id_type является обязательным. Укажите корректный параметр id_type.'),
  e30007(30007, 'INVALID_ARGUMENT', 'Missing parameter: id',
      'Входной параметр id является обязательным. Укажите корректный параметр id.'),
  e30008(30008, 'INVALID_ARGUMENT', 'Missing parameter: figi',
      'Входной параметр figi является обязательным. Укажите корректный параметр figi.'),
  e30009(30009, 'INVALID_ARGUMENT', 'from is invalid',
      'Входной параметр from имеет некорректное значение. Укажите корректный параметр from.'),
  e30010(30010, 'INVALID_ARGUMENT', 'to is invalid',
      'Входной параметр to имеет некорректное значение. Укажите корректный параметр to.'),
  e30011(30011, 'INVALID_ARGUMENT', 'interval is invalid', 'Входной параметр interval имеет некорректное значение.'),
  e30012(30012, 'INVALID_ARGUMENT', 'to can\'t be less than from',
      'Входной параметр to не может быть меньше параметра from. Укажите корректные параметры from и to.'),
  e30013(30013, 'INVALID_ARGUMENT', 'class_code require for id_type = ticker',
      'Входной параметр class_code не может быть пустым при поиске по тикеру. Укажите корректный параметр class_code.'),
  e30014(30014, 'INVALID_ARGUMENT', 'The maximum request period for the given candle interval has been exceeded',
      'Превышен максимальный период запроса для данного интервала свечи. Укажите корректный интервал.'),
  e30015(30015, 'INVALID_ARGUMENT', 'Parameter quantity is missing or equal to 0',
      'Входной параметр quantity является обязательнымУкажите корректный параметр quantity.'),
  e30016(30016, 'INVALID_ARGUMENT', 'quantity is invalid',
      'Входной параметр quantity имеет некорректное значение. Укажите корректный параметр quantity.'),
  e30017(30017, 'INVALID_ARGUMENT', 'Missing parameter: price',
      'Входной параметр price является обязательным. Укажите корректный параметр price. Значение параметра price должно быть положительным. units и nanos не могут иметь разные знак, модуль nanos должен быть < 999 999 999.'),
  e30018(30018, 'INVALID_ARGUMENT', 'price is invalid',
      'Входной параметр price имеет некорректное значение. Укажите корректный параметр price.'),
  e30019(30019, 'INVALID_ARGUMENT', 'Missing parameter: direction',
      'Входной параметр direction является обязательным. Укажите корректный параметр direction.'),
  e30020(30020, 'INVALID_ARGUMENT', 'direction is invalid', 'Входной параметр direction имеет некорректное значение.'),
  e30021(30021, 'INVALID_ARGUMENT', 'Missing parameter: account_id',
      'Входной параметр account_id является обязательным. Укажите корректный параметр account_id.'),
  e30022(30022, 'INVALID_ARGUMENT', 'Missing parameter: state',
      'Входной параметр state является обязательным. Укажите корректный параметр state. Список доступных значений: direction.'),
  e30023(30023, 'INVALID_ARGUMENT', 'invalid parameter: state',
      'Входной параметр state имеет некорректное значение. Укажите корректный параметр state. Список доступных значений: direction.'),
  e30025(30025, 'INVALID_ARGUMENT', 'Missing parameter: order_type',
      'Входной параметр order_type является обязательным. Укажите корректный параметр order_type. Список доступных значений: order_type.'),
  e30026(30026, 'INVALID_ARGUMENT', 'invalid parameter: order_type',
      'Входной параметр order_type имеет некорректное значение. Укажите корректный параметр order_type.'),
  e30027(30027, 'INVALID_ARGUMENT', 'Missing parameter: order_id',
      'Входной параметр order_id является обязательным. Укажите корректный параметр order_id.'),
  e30028(30028, 'INVALID_ARGUMENT', 'order id is invalid UUID format.',
      'Входной параметр order_id имеет некорректное значение. Укажите корректный параметр order_id формата UUID. Максимальная длина — 36 символов.'),
  e30029(30029, 'INVALID_ARGUMENT', 'Missing parameter: idempotency_key',
      'Входной параметр idempotency_key является обязательным. Укажите корректный параметр idempotency_key.'),
  e30030(30030, 'INVALID_ARGUMENT', 'idempotency_key is invalid',
      'Входной параметр idempotency_key имеет некорректное значение. Укажите корректный параметр idempotency_key. Максимальная длина — 36 символов.'),
  e30031(30031, 'INVALID_ARGUMENT', 'Missing parameter: depth',
      'Входной параметр depth является обязательным. Укажите корректный параметр depth.'),
  e30032(30032, 'INVALID_ARGUMENT', 'depth is invalid',
      'Входной параметр depth имеет некорректное значение. Укажите корректный параметр depth.'),
  e30033(30033, 'INVALID_ARGUMENT', 'Missing parameter: trade_clearing_account or class_code',
      'Параметр trade_clearing_account или class_code не может быть пустым.'),
  e30034(30034, 'INVALID_ARGUMENT', 'Not enough balance',
      'Недостаточно средств для совершения сделки (ошибка песочницы). Пополните баланс нужной валюты через метод SandboxPayIn.'),
  e30036(30036, 'INVALID_ARGUMENT', 'Missing parameter: stop_price',
      'Входной параметр stop_price является обязательным. Укажите корректный параметр stop_price.'),
  e30037(30037, 'INVALID_ARGUMENT', 'Missing parameter: stop_order_type',
      'Входной параметр stop_order_type является обязательным. Укажите корректный параметр stop_order_type.'),
  e30038(30038, 'INVALID_ARGUMENT', 'stop_order_type is invalid',
      'Входной параметр stop_order_type имеет некорректное значение.'),
  e30039(
      30039, 'INVALID_ARGUMENT', 'Bad request: trailing_data', 'Укажите корректное значение параметра trailing_data.'),
  e30040(30040, 'INVALID_ARGUMENT', 'expire_date is invalid',
      'Входной параметр expire_date имеет некорректное значение. Укажите корректный параметр expire_date.'),
  e30041(30041, 'INVALID_ARGUMENT', 'The method is available only for futures',
      'Метод предназначен только для работы с фьючерсами. Передайте во входные параметры метода идентификатор фьючерса.'),
  e30042(30042, 'INVALID_ARGUMENT', 'Not enough assets for a margin trade',
      'Недостаточно активов для маржинальной сделки.  Проверьте маржинальные показатели счёта — это можно сделать через метод GetMarginAttributes.'),
  e30043(30043, 'INVALID_ARGUMENT', 'Missing parameter: expiration_type',
      'Входной параметр expiration_type является обязательным. Укажите корректный параметр expiration_type.'),
  e30044(30044, 'INVALID_ARGUMENT', 'expiration_type is invalid',
      'Входной параметр expiration_type имеет некорректное значение.'),
  e30045(30045, 'INVALID_ARGUMENT', 'Missing parameter: ticker',
      'Входной параметр ticker является обязательным. Укажите корректный параметр ticker.'),
  e30047(30047, 'INVALID_ARGUMENT', 'Price currency does not match the settlement currency',
      'Валюта цены не совпадает с валютой расчётов по инструменту. Укажите корректную валюту цены. Узнать валюту расчёта конкретного инструмента можно через метод GetInstrumentBy.'),
  e30048(30048, 'INVALID_ARGUMENT', 'Instrument type is not bond',
      'Метод предназначен только для запроса информации по облигации. Передайте во входные параметры метода идентификатор облигации.'),
  e30049(30049, 'INVALID_ARGUMENT', 'Post order error: %s', 'Ошибка метода выставления торгового поручения.'),
  e30050(30050, 'INVALID_ARGUMENT', 'instrument_status is invalid',
      'Входной параметр instrument_status имеет некорректное значение.'),
  e30051(30051, 'INVALID_ARGUMENT', 'Account margin status is disabled',
      'Для данного договора недоступна маржинальная торговля. Чтобы выставлять поручения на срочном рынке, включите маржинальную торговлю в приложении и терминале.'),
  e30052(30052, 'INVALID_ARGUMENT', 'Instrument forbidden for trading by API',
      'Для данного инструмента торговля через API недоступна.  Вы можете проверить значение параметра api_trade_available_flag инструмента через метод GetTradingStatus.'),
  e30053(30053, 'INVALID_ARGUMENT', 'Post stop_order error: %s', 'Ошибка метода выставления стоп-заявки.'),
  e30054(30054, 'INVALID_ARGUMENT', 'Instrument type is not a share or etf',
      'Тип инструмента не инвестиционный фонд или акция.'),
  e30055(30055, 'INVALID_ARGUMENT', 'order_id cannot be longer than 36 characters',
      'order_id не может быть длиннее 36 символов.'),
  e30056(30056, 'INVALID_ARGUMENT', 'Stop order settlement currency is not supported',
      'Валюта выставления стоп-заявки не поддерживается.'),
  e30057(30057, 'INVALID_ARGUMENT', 'The order is a duplicate, but the order report was not found',
      'Заявка является дублем, но отчёт по заявке не найден. Проверьте параметр order_id (идентификатор запроса выставления поручения для целей идемпотентности) — он должен быть уникальным.'),
  e30058(30058, 'INVALID_ARGUMENT', 'Task not completed yet, please try again later',
      'Выполнение задачи ещё не завершено, попробуйте позже.'),
  e30059(30059, 'INVALID_ARGUMENT', 'Cancel order error: %s', 'Ошибка метода отмены заявки.'),
  e30060(30060, 'INVALID_ARGUMENT', 'Cancel stop-order error: %s', 'Ошибка метода отмены стоп-заявки.'),
  e30061(30061, 'INVALID_ARGUMENT', 'from value out of range',
      'Входной параметр from имеет некорректное значение. Укажите значение в пределах от 1970-01-01T00:00:00Z до 2099-12-31T23:59:59.999999999Z включительно.'),
  e30062(30062, 'INVALID_ARGUMENT', 'to value out of range',
      'Входной параметр to имеет некорректное значение. Укажите значение в пределах от 1970-01-01T00:00:00Z до 2099-12-31T23:59:59.999999999Z включительно.'),
  e30063(30063, 'INVALID_ARGUMENT', 'expire_date value out of range',
      'Входной параметр expire_date имеет некорректное значение. Дата должна быть не ранее текущей и не позднее 2099-12-31T23:59:59.999999999Z.'),
  e30064(30064, 'INVALID_ARGUMENT', 'The required period should not exceed 31 days',
      'Запрошенный период не может превышать 31 дня. Укажите корректный период.'),
  e30065(30065, 'INVALID_ARGUMENT', 'Missing parameter: task_id',
      'Входной параметр task_id является обязательным. Укажите корректный параметр task_id.'),
  e30066(30066, 'INVALID_ARGUMENT', 'Missing parameter: payload',
      'Входной параметр payload является обязательным. Укажите корректный параметр payload.'),
  e30067(30067, 'INVALID_ARGUMENT', 'action_type is invalid',
      'Некорректное значение action_type. Выберите допустимое значение.'),
  e30068(30068, 'INVALID_ARGUMENT', 'Only limit order is allowed',
      'В настоящий момент возможно выставление только лимитного торгового поручения.  Подробнее про выставление торговых поручений'),
  e30069(30069, 'INVALID_ARGUMENT', 'Invalid parameter: limit',
      'Входной параметр limit имеет некорректное значение. Значение должно быть меньше или равно 1000.'),
  e30070(30070, 'INVALID_ARGUMENT', 'from can\'t be more than the current date',
      'Входной параметр from имеет некорректное значение. Укажите значение, которое не превышает текущую дату и время.'),
  e30077(30077, 'INVALID_ARGUMENT', 'Not available for OTC instruments',
      'Метод недоступен для внебиржевых инструментов. У таких инструментов параметр api_trade_available_flag метода GetTradingStatus будет иметь значение false.'),
  e30078(30078, 'INVALID_ARGUMENT', 'Incorrect minimum price increment',
      'Некорректный шаг изменения цены. Остаток от деления price на min_price_increment должен быть равен 0.'),
  e30079(30079, 'INVALID_ARGUMENT', 'Instrument is not available for trading',
      'Инструмент недоступен для торгов.  Подробнее о торговых статусах'),
  e30080(30080, 'INVALID_ARGUMENT', 'Quantity must be positive', 'Количество лотов должно быть положительным числом.'),
  e30081(30081, 'INVALID_ARGUMENT', 'Account status is closed', 'Аккаунт закрыт.'),
  e30082(30082, 'INVALID_ARGUMENT', 'Account status is blocked', 'Аккаунт заблокирован.'),
  e30083(30083, 'INVALID_ARGUMENT', 'order_type is invalid', 'Некорректный тип заявки.'),
  e30084(
      30084, 'INVALID_ARGUMENT', 'Maximum request period has been exceeded', 'Превышен лимит запрашиваемого периода.'),
  e30085(30085, 'INVALID_ARGUMENT', 'Price in points is available only for futures and bonds',
      'Тип цены в пунктах доступен только для фьючерсов и облигаций.'),
  e30086(30086, 'INVALID_ARGUMENT', 'Year is invalid', 'Некорректный год.'),
  e30087(30087, 'INVALID_ARGUMENT', 'Missing parameter: query',
      'Входной параметр query является обязательным. Укажите не пустой параметр query.'),
  e30088(30088, 'INVALID_ARGUMENT', 'from and to must have the same year',
      'Запрашиваемые даты должны быть в рамках одного года.'),
  e30089(30089, 'INVALID_ARGUMENT', 'to must not be later than %s',
      'Поле to не должно быть позднее даты, указанной в тексте ошибки. Дата указана в формате ISO 8601.'),
  e30090(30090, 'INVALID_ARGUMENT', 'Missing parameter: siebel_id',
      'Входной параметр siebel_id является обязательным. Укажите корректный параметр siebel_id.'),
  e30091(30091, 'INVALID_ARGUMENT', 'Quantity of instruments can`t be more than 100',
      'Количество инструментов не может превышать 100.'),
  e30092(30092, 'INVALID_ARGUMENT', 'Trading unavailable on weekends',
      'Торги недоступны по нерабочим дням.  Подробнее о торговых сессиях'),
  e30093(30093, 'INVALID_ARGUMENT', 'Missing parameter: figi or instrument_id',
      'Один из параметров — figi или instrument_id — является обязательным.'),
  e30094(30094, 'INVALID_ARGUMENT', 'Options trading is not available at the moment',
      'Выставление заявок по опционам недоступно.'),
  e30095(30095, 'INVALID_ARGUMENT', 'The request was not executed by the exchange',
      'Заявка не исполнена биржей. Лимитная заявка может не исполняться, потому что не достигла установленной цены на бирже. Рыночная — из-за отсутствия сделок с данными инструментов, то есть низкой ликвидности.'),
  e30096(30096, 'INVALID_ARGUMENT', 'The order was rejected, try again later',
      'Заявка отклонена, попробуйте повторить позже.'),
  e30097(30097, 'INVALID_ARGUMENT', 'Inappropriate trading session',
      'Сейчас эта сессия не идёт.  Подробнее о торговых сессиях'),
  e30098(30098, 'INVALID_ARGUMENT', 'Currently, there is no trading on this financial instrument',
      'Торги по этому финансовому инструменту сейчас не проводятся. Проверить актуальный торговый статус инструмента можно через метод GetTradingStatus.'),
  e30099(30099, 'INVALID_ARGUMENT', 'The price is outside the limits for this instrument',
      'Цена вне лимитов по инструменту или сделки вне лимита. Подробнее про выставление торговых поручений'),
  e30100(30100, 'INVALID_ARGUMENT', 'The price must be positive', 'Цена должна быть положительной.'),
  e30101(30101, 'INVALID_ARGUMENT', 'To trade this financial instrument, pass the test',
      'Для торговли этим инструментом пройдите тестирование. Подробнее про тестирование.'),
  e30102(30102, 'INVALID_ARGUMENT', 'Required parameters Missing', 'Обязательные параметры указаны неправильно.'),
  e30103(30103, 'INVALID_ARGUMENT', 'Only best price is allowed',
      'Для инструмента можно выставить заявки только с типом «лучшая цена».'),
  e30104(30104, 'INVALID_ARGUMENT', 'price_type is invalid',
      'Некорректное значение price_type. Значением price_type может быть только PRICE_TYPE_POINT или PRICE_TYPE_CURRENCY.'),
  e30105(30105, 'INVALID_ARGUMENT', 'exchange_order_type is invalid',
      'Некорректное значение exchange_order_type. Значением exchange_order_type может быть только LIMIT или MARKET.'),
  e30106(30106, 'INVALID_ARGUMENT', 'status is invalid',
      'Некорректное значение status. Значением status может быть только ACTIVE, EXECUTED, CANCELED или EXPIRED.'),
  e30107(30107, 'INVALID_ARGUMENT', 'Negative values are not allowed',
      'Некорректное значение limit и/или page. Параметры limit и page не могут принимать отицательные значения.'),
  e30108(30108, 'INVALID_ARGUMENT', 'Specify a lower limit or page value because there are fewer brands',
      'Количество брендов меньше запрашиваемых параметров.'),
  e30109(30109, 'INVALID_ARGUMENT', 'Maximum transaction amount has been exceeded',
      'Превышена максимальная сумма сделки. Разделите ордер на несколько ордеров меньшего объема.'),
  e30210(30210, 'INVALID_ARGUMENT', 'Trailing data required',
      'Проверьте параметры запроса стоп-заявки. Не заданы indent или spread.'),
  e30211(30211, 'INVALID_ARGUMENT', 'indent type required',
      'Проверьте параметры запроса стоп-заявки. Не задан indent_type.'),
  e30212(30212, 'INVALID_ARGUMENT', 'spread type required',
      'Проверьте параметры запроса стоп-заявки. Не задан spread_type.'),
  e30213(30213, 'INVALID_ARGUMENT', 'indicator_type is invalid',
      'Проверьте параметры запроса. Некорректный indicator_type.'),
  e30214(30214, 'INVALID_ARGUMENT', 'type_of_price is invalid',
      'Проверьте параметры запроса. Некорректный type_of_price.'),
  e30215(30215, 'INVALID_ARGUMENT', 'length is invalid', 'Проверьте параметры запроса. Некорректный length.'),
  e30216(30216, 'INVALID_ARGUMENT', 'deviation_data is invalid',
      'Проверьте параметры запроса. Некорректный параметр deviation_data.'),
  e30217(30217, 'INVALID_ARGUMENT', 'smoothing_data is invalid',
      'Проверьте параметры запроса. Некорректный параметр smoothing_data.'),
  e30218(30218, 'INVALID_ARGUMENT', 'Quantity of instruments can`t be more than 3000',
      'Количество инструментов в списке не может быть больше 3000.'),
  e30219(30219, 'INVALID_ARGUMENT', 'input candle_source_type is invalid',
      'Проверьте параметры запроса. Некорректный параметр candle_source_type.'),
  e35001(35001, 'INVALID_ARGUMENT', 'Sandbox accounts limit reached',
      'Достигнут лимит на открытие торговых счетов в песочнице. Чтобы открыть новый счёт, закройте один из существующих.'),
  e40002(40002, 'PERMISSION_DENIED', 'Insufficient privileges',
      'Недостаточно прав для совершения операции. Токен доступа имеет уровень прав read-only или у токена нет доступа к указанному счёту.  Подробнее про виды токенов'),
  e40003(40003, 'UNAUTHENTICATED', 'Authentication token is missing or invalid',
      'Токен доступа не найден или неактивен. Новый токен можно выпустить в личном кабинете.'),
  e40004(40004, 'PERMISSION_DENIED', 'Working with orders is not available with this account',
      'Выставление заявок недоступно с текущего аккаунта.  Брокерский счёт не найден, не принадлежит пользователю или закрыт. Возможно, на пользователе ограничения от T-Invest API или от биржи — в этом случае обратитесь в техподдержку.'),
  e50001(50001, 'NOT_FOUND', 'Exchange not found',
      'Биржа не найдена по переданному exchange_id. Укажите корректный exchange_id.'),
  e50002(50002, 'NOT_FOUND', 'Instrument not found',
      'Инструмент не найден. Укажите корректный идентификатор инструмента.'),
  e50004(50004, 'NOT_FOUND', 'Account not found',
      'Счёт по переданному account_id не найден. Укажите корректный account_id.'),
  e50005(50005, 'NOT_FOUND', 'Order not found',
      'Торговое поручение по переданному order_id не найдено. Укажите корректный order_id.'),
  e50006(50006, 'NOT_FOUND', 'Stop-order not found',
      'Стоп-заявка по переданному stop_order_id не найдена. Укажите корректный stop_order_id.'),
  e50007(50007, 'NOT_FOUND', 'Task not found', 'Задача не найдена.'),
  e50008(50008, 'NOT_FOUND', 'No order book provider', 'Отсутствует источник данных по стаканам.'),
  e50009(50009, 'NOT_FOUND', 'Asset not found', 'Актив не найден. Укажите корректный идентификатор актива.'),
  e50010(50010, 'NOT_FOUND', 'Brand not found', 'Бренд не найден. Укажите корректный идентификатор бренда.'),
  e70001(70001, 'INTERNAL', 'Internal error',
      'Внутренняя ошибка сервиса.  Если ошибка повторяется, обратитесь в службу технической поддержки.'),
  e70002(70002, 'INTERNAL', 'Internal network error',
      'Неизвестная сетевая ошибка, попробуйте выполнить запрос позднее. Если ошибка повторяется, обратитесь в службу технической поддержки.'),
  e70003(70003, 'INTERNAL', 'Internal error, please try again later',
      'Внутренняя ошибка сервиса, попробуйте выполнить запрос позже.  Если ошибка повторяется, обратитесь в службу технической поддержки.'),
  e80001(80001, 'RESOURCE_EXHAUSTED	', 'Limit of open streams exceeded',
      'Превышен лимит одновременных открытых stream-соединений.'),
  e80002(80002, 'RESOURCE_EXHAUSTED', 'Request limit exceeded', 'Превышен лимит запросов в минуту.'),
  e80003(80003, 'RESOURCE_EXHAUSTED	', 'The limit on SMS sending has been exceeded, try again in a minute',
      'Превышен лимит на отправку СМС, попробуйте через минуту. Если вы не хотите получать СМС при выставлении заявки, отключите отправку СМС в личном кабинете.'),
  e80004(80004, 'RESOURCE_EXHAUSTED	', 'No active subscriptions', 'В стриме отсутствуют активные подписки.'),
  e90001(90001, 'FAILED_PRECONDITION', 'Need confirmation: %s', 'Требуется подтверждение операции.'),
  e90002(90002, 'FAILED_PRECONDITION', 'Only for qualified investors',
      'Торговля этим инструментом доступна только квалифицированным инвесторам.'),
  e90003(90003, 'FAILED_PRECONDITION', 'The price is too high',
      'Цена заявки слишком высокая. Разбейте заявку на заявки меньшего размера.');

  final int code;
  final String type;
  final String message;
  final String reason;

  const TinkoffInvestmentError(
    this.code,
    this.type,
    this.message,
    this.reason,
  );

  static TinkoffInvestmentError fromValue(String? value) => value == null
      ? unknown
      : TinkoffInvestmentError.values.firstWhere((e) => e.code == int.parse(value), orElse: () => unknown);

  @override
  String toString() {
    return 'Thrown exception!\ncode: $code, type: $type\nMessage: $message\nReason: $reason';
  }
}
